### ISSUE TITLE
Changes / Todo upstream merge

### ISSUE THREAD

**Issue by Hedius** [Hedius/puppet-clickhouse#1]
Probably will have to discuss a few of my changes. Not sure if they can be merged upstream since I partly revert deric's changes to storing user configs in conf.d. Reason: I try to match a default clickhouse as much as possible. 

# Changes
1. use `<clickhouse> ` instead of `<yandex>` in XML files.
2. Write most config files as yaml instead of xml to remove the **xmlsimple** dependency. https://clickhouse.com/docs/en/operations/configuration-files ClickHouse supports mixing yaml and xml config files. switch works inplace without breaking clickhouse. (At least on my databases :) )
3. `conf.d` is replaced with `config.d`
4. quotas.yaml, profiles.yaml and users.xml get stored in `users.d` again. Matches the previous behavior of the module. + the documentation of the module is mostly correct again.
5. users.xml does not get wiped by default anymore. It did before, but the documentation was incorrect here. Not updated. Maybe set by default to true + fix the documentation.
6. users.xml is parsed again / used again. so the param for it makes sense again.
7. Updates the domain for all URLs to `clickhouse.com`
8. Restricted folder permissions. = Removed the other permissions for most of them. Is there a reason why it was 775 on most folders?...
9. Updated the systemd unit to match the one currently used by clickhouse.

# ToDo
- [x] Update tests for yaml.
- [x] Remove conf.d directory
- [x] Remove config.xml

**Comment by Hedius** [comment]
added: conf.d is no longer used. config.d instead.

conf.d was the default directory in the past. But for a few years clickhouse has been using config.d instead.

If you deploy a new clickhouse you have duplicate folders...

**Comment by Hedius** [comment]
Another todo.  The current apt logic deploys the key using the deprecated method.

**Comment by Hedius** [comment]
tests fixt.

no longer deploying a systemd unit. using a dropin instead
